"""followers

Revision ID: 769e2c2294dc
Revises: 6b7c08063038
Create Date: 2020-11-24 15:39:02.894986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769e2c2294dc'
down_revision = '6b7c08063038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
